# Build the Pocketbase binary
build:
	go build -o pocketbase main.go

# Serve compiled Pocketbase client
serve:
	./pocketbase.go serve

# Serve source/dev Pocketbase client
serve-dev:
	go run main.go serve
