# Build the Pocketbase binary
api-build:
	go build -o pocketbase main.go

# Serve compiled Pocketbase client
api-serve:
	./pocketbase.go serve

# Serve source/dev Pocketbase client
api-serve-dev:
	go run main.go serve
